[package]
name = "lit"
description = "LOOP Just In Time Interpreter"
version = "0.1.0"
authors = ["bmahmoud <bmahmoud@mpi-cbg.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
num-bigint = "0.4.0"
num-traits = "0.2.14"
enum-display-derive = "0.1.1"
rand = "0.8.3"
bitflags = "1.2.1"