name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: wasm-pack-action
      uses: jetli/wasm-pack-action@v0.3.0
    - name: Build WASM
      run: wasm-pack build --verbose
    - name: Run tests
      run: cargo test --verbose
