name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: ./engine

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Install Requirements
    - uses: actions/checkout@v2
    - name: Setup node 14
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        registry-url: 'https://npm.pkg.github.com'
        scope: '@indietyp'
    - name: Install Quicktype
      run: npm i -g quicktype
    - name: Install wasm-pack
      uses: jetli/wasm-pack-action@v0.3.0
    - name: Install zip
      uses: montudor/action-zip@v1
    # Build WASM
    - name: Build WASM
      run: wasm-pack build --target=web
    # TypeScript Definitions from JSON-Schema
    - name: Generate Schema
      run: cargo run --package lit --features cli --bin lit schema --mode overwrite --output pkg/schema/
    - name: Generate TypeScript Definitions
      run: quicktype pkg/schema/root.json -o pkg/schema.ts -s schema --just-types --acronym-style original --nice-property-names --explicit-unions
    # Upload Artifacts to GitHub
    - run: npm install
      working-directory: ./engine/pkg
    - run: npm publish
      working-directory: ./engine/pkg
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
